services:
  db:
    image: postgis/postgis:17-3.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local

  martin:
    image: ghcr.io/maplibre/martin:v0.13.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://root:mysecretpassword@db/local
    volumes:
      - ./martin.yml:/etc/martin.yml
    depends_on:
      - db
    command: --config /etc/martin.yml